name: Build lint test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Git-Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

     